# Generated by Django 5.2.17 on 2026-10-05 14:05

from django.db import migrations


def mark_existing_users_verified(apps, schema_editor):
    """Sign-up now waits for admin approval; everyone who already has an account is using
    the app, so they count as approved."""
    User = apps.get_model('users', 'User')
    User.objects.filter(is_verified=False).update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        # Nothing to undo: going back leaves everyone approved.
        migrations.RunPython(mark_existing_users_verified, migrations.RunPython.noop),
    ]
