# Generated by Django 5.2.17 on 2026-10-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="session",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="studentclassroom",
            name="joined_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentclassroom",
            name="left_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
