# Generated by Django 5.2.17 on 2026-10-05 14:20

from django.db import migrations


def add_missing_main_classrooms(apps, schema_editor):
    """Every semester has one hidden class group ("Main"). Semesters made before that rule
    without any classroom get one now (no students, no courses: nothing else changes)."""
    Semester = apps.get_model('academic', 'Semester')
    Classroom = apps.get_model('academic', 'Classroom')
    with_classroom = Classroom.objects.filter(deleted=False).values_list('semester_id', flat=True)
    missing = Semester.objects.exclude(id__in=with_classroom)
    Classroom.objects.bulk_create([Classroom(name='Main', semester=semester) for semester in missing])


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_semester_session_membership_dates"),
    ]

    operations = [
        # Nothing to undo: an empty class group is harmless.
        migrations.RunPython(add_missing_main_classrooms, migrations.RunPython.noop),
    ]
