# Generated by Django 5.2.17 on 2026-10-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancelog",
            name="source",
            field=models.CharField(
                choices=[
                    ("HARDWARE", "Hardware"),
                    ("QR_ONLINE", "QR Online"),
                    ("QR_OFFLINE", "QR Offline"),
                    ("MANUAL", "Manual"),
                    ("FACE", "Face"),
                ],
                default="MANUAL",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="attendancesession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("FINGERPRINT", "Fingerprint"),
                    ("QR_ONLINE", "QR Online"),
                    ("QR_OFFLINE", "QR Offline"),
                    ("FACE", "Face"),
                ],
                max_length=15,
            ),
        ),
    ]
