# Generated by Django 5.2.17 on 2026-10-04 21:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pose",
                    models.CharField(
                        choices=[
                            ("STRAIGHT", "Straight"),
                            ("LEFT", "Left"),
                            ("RIGHT", "Right"),
                        ],
                        max_length=10,
                    ),
                ),
                ("crop_jpeg", models.BinaryField()),
                ("embedding", models.BinaryField()),
                ("engine", models.CharField(max_length=50)),
                ("consented_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["student", "pose"],
                "unique_together": {("student", "pose")},
            },
        ),
    ]
